### ISSUE TITLE
Instance reuse fails for non-default JSON Schema implementations

### ISSUE THREAD

**Issue by textbook** [up9cloud/chai-json-schema-ajv#68]
Per [the AJV docs][1] to use e.g. draft-2020-12 you need to import a specific implementation:

```javascript
const Ajv2020 = require("ajv/dist/2020")
const ajv = new Ajv2020()
```

I assumed I'd be able to pass this instance as the `ajv` option to `.create`, per [your docs][2] but due to this `instanceof` check:

https://github.com/up9cloud/chai-json-schema-ajv/blob/04f0fcdcc3d418307e41baa970f77e35035cf5d8/src/index.js#L5-L9

a new instance of the vanilla `Ajv` is created. It would likely be better to test against `AjvCore` from `ajv/dist/core`, as this is extended by all of the various implementations, or even to just use `options.ajv` if it's provided.

  [1]: https://ajv.js.org/json-schema.html#draft-2020-12
  [2]: https://www.npmjs.com/package/chai-json-schema-ajv#option-ajv

**Comment by up9cloud** [comment]
@textbook fixed.
